### ISSUE TITLE
Security vulnerabilities: Upgrade dependencies

### ISSUE THREAD

**Issue by dialex** [jwarby/inquirer-maxlength-input-prompt#1]
Currently your project has 66 of these:

<img width="647" alt="Screenshot 2020-04-25 at 15 05 15" src="https://user-images.githubusercontent.com/2140450/80281890-38c1cd00-8706-11ea-8ca6-874bdb8574c7.png">

Can you please update your dependencies (specially Jest)?

**Comment by dialex** [comment]
Does it help if I create a PR with all dependencies upgraded? @jwarby

**Comment by jwarby** [comment]
https://github.com/jwarby/inquirer-maxlength-input-prompt/releases/tag/v1.0.1
